# for the-plain theme
author_name: yee
logo_url: https://avatars.githubusercontent.com/u/73866496?v=4
title: yee
social_share_previews: true

plugins:
  - jekyll-remote-theme
remote_theme: heiswayi/the-plain
