# for the-plain theme
author_name: yee
book_logo_url: /assets/book_logo.jpg
drama_logo_url: /assets/drama_logo.jpg
title: yee
social_share_previews: true

plugins:
  - jekyll-remote-theme
remote_theme: heiswayi/the-plain
