url: https://read.yeekuo.tw

# for the-plain theme
author_name: yee
book_logo_url: /assets/book_logo.png
drama_logo_url: /assets/drama_logo.png
title: yee
social_share_previews: true

plugins:
  - jekyll-remote-theme
remote_theme: heiswayi/the-plain
